version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: nest-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
